#############################################################################
# Makefile for building: auth
# Generated by qmake (3.1) (Qt 6.1.3)
# Project:  auth.pro
# Template: subdirs
# Command: C:\Qt\6.1.3\mingw81_64\bin\qmake.exe -o Makefile auth.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\6.1.3\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\6.1.3\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\6.1.3\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-Qt-Secret \
		sub-MyProject \
		sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro


sub-Qt-Secret-qmake_all:  FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd Qt-Secret\ && $(MAKE) -f Makefile qmake_all
sub-Qt-Secret: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Qt-Secret-make_first-ordered: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Qt-Secret-make_first: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Qt-Secret-all-ordered: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Qt-Secret-all: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Qt-Secret-clean-ordered: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Qt-Secret-clean: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Qt-Secret-distclean-ordered: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Qt-Secret-distclean: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Qt-Secret-install_subtargets-ordered: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Qt-Secret-install_subtargets: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Qt-Secret-uninstall_subtargets-ordered: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Qt-Secret-uninstall_subtargets: FORCE
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-MyProject-qmake_all: sub-Qt-Secret-qmake_all FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd MyProject\ && $(MAKE) -f Makefile qmake_all
sub-MyProject: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-MyProject-make_first-ordered: sub-Qt-Secret-make_first-ordered  FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-MyProject-make_first: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-MyProject-all-ordered: sub-Qt-Secret-all-ordered  FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-MyProject-all: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-MyProject-clean-ordered: sub-Qt-Secret-clean-ordered  FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-MyProject-clean: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-MyProject-distclean-ordered: sub-Qt-Secret-distclean-ordered  FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-MyProject-distclean: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-MyProject-install_subtargets-ordered: sub-Qt-Secret-install_subtargets-ordered  FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-MyProject-install_subtargets: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-MyProject-uninstall_subtargets-ordered: sub-Qt-Secret-uninstall_subtargets-ordered  FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-MyProject-uninstall_subtargets: FORCE
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-qmake_all: sub-MyProject-qmake_all FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd Qt-Secret\src\ && $(MAKE) -f Makefile.Qt-Secret qmake_all
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-make_first-ordered: sub-MyProject-make_first-ordered  FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret 
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-make_first: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret 
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-all-ordered: sub-MyProject-all-ordered  FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret all
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-all: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret all
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-clean-ordered: sub-MyProject-clean-ordered  FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret clean
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-clean: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret clean
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-distclean-ordered: sub-MyProject-distclean-ordered  FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret distclean
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-distclean: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret distclean
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-install_subtargets-ordered: sub-MyProject-install_subtargets-ordered  FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret install
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-install_subtargets: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret install
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-uninstall_subtargets-ordered: sub-MyProject-uninstall_subtargets-ordered  FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret uninstall
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-uninstall_subtargets: FORCE
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret uninstall

Makefile: auth.pro ../../Qt/6.1.3/mingw81_64/mkspecs/win32-g++/qmake.conf ../../Qt/6.1.3/mingw81_64/mkspecs/features/spec_pre.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/device_config.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/common/sanitize.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/common/gcc-base.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/common/g++-base.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/common/windows-vulkan.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/common/g++-win32.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/common/windows-desktop.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/qconfig.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_activeqt.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_activeqt_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachine.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/qt_functions.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/qt_config.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/win32-g++/qmake.conf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/toolchain.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/default_pre.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/win32/default_pre.prf \
		Qt-Secret/src/mini-gmp/src/GMPIncudePah.pri \
		Qt-Secret/src/mini-gmp/src/ccache.pri \
		Qt-Secret/src/mini-gmp/src/GMP.pri \
		Qt-Secret/src/mini-gmp/GMP.pri \
		Qt-Secret/src/Qt-Secret.pri \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/resolve_config.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/default_post.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/qtquickcompiler.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/entrypoint.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/precompile_header.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/warn_on.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/qmake_use.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/file_copies.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/win32/windows.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/testcase_targets.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/exceptions.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/yacc.prf \
		../../Qt/6.1.3/mingw81_64/mkspecs/features/lex.prf \
		auth.pro
	$(QMAKE) -o Makefile auth.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
../../Qt/6.1.3/mingw81_64/mkspecs/features/spec_pre.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/device_config.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/common/sanitize.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/common/gcc-base.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/common/g++-base.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/common/windows-vulkan.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/common/g++-win32.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/common/windows-desktop.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/qconfig.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_ext_freetype.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_ext_libpng.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_activeqt.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_activeqt_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axbase_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axcontainer.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axserver.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_axserver_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core5compat.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core5compat_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_linguist.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxmlqml.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_shadertools.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachine.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachine_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachineqml.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/features/qt_functions.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/qt_config.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/win32-g++/qmake.conf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/6.1.3/mingw81_64/mkspecs/features/exclusive_builds.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/toolchain.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/default_pre.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/win32/default_pre.prf:
Qt-Secret/src/mini-gmp/src/GMPIncudePah.pri:
Qt-Secret/src/mini-gmp/src/ccache.pri:
Qt-Secret/src/mini-gmp/src/GMP.pri:
Qt-Secret/src/mini-gmp/GMP.pri:
Qt-Secret/src/Qt-Secret.pri:
../../Qt/6.1.3/mingw81_64/mkspecs/features/resolve_config.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/default_post.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/qtquickcompiler.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/entrypoint.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/precompile_header.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/warn_on.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/qmake_use.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/file_copies.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/win32/windows.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/testcase_targets.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/exceptions.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/yacc.prf:
../../Qt/6.1.3/mingw81_64/mkspecs/features/lex.prf:
auth.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile auth.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: sub-Qt-Secret-qmake_all sub-MyProject-qmake_all sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-qmake_all FORCE

make_first: sub-Qt-Secret-make_first-ordered sub-MyProject-make_first-ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-make_first-ordered  FORCE
all: sub-Qt-Secret-all-ordered sub-MyProject-all-ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-all-ordered  FORCE
clean: sub-Qt-Secret-clean-ordered sub-MyProject-clean-ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-clean-ordered  FORCE
distclean: sub-Qt-Secret-distclean-ordered sub-MyProject-distclean-ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Qt-Secret-install_subtargets-ordered sub-MyProject-install_subtargets-ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Qt-Secret-uninstall_subtargets-ordered sub-MyProject-uninstall_subtargets-ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-uninstall_subtargets-ordered FORCE

sub-Qt-Secret-debug_ordered:
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-MyProject-debug_ordered: sub-Qt-Secret-debug_ordered 
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-debug_ordered: sub-MyProject-debug_ordered 
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret debug
debug: sub-Qt-Secret-debug_ordered sub-MyProject-debug_ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-debug_ordered

sub-Qt-Secret-release_ordered:
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-MyProject-release_ordered: sub-Qt-Secret-release_ordered 
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-release_ordered: sub-MyProject-release_ordered 
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret release
release: sub-Qt-Secret-release_ordered sub-MyProject-release_ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-release_ordered

sub-Qt-Secret-check_ordered:
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-MyProject-check_ordered: sub-Qt-Secret-check_ordered 
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-check_ordered: sub-MyProject-check_ordered 
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret check
check: sub-Qt-Secret-check_ordered sub-MyProject-check_ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-check_ordered

sub-Qt-Secret-benchmark_ordered:
	@if not exist Qt-Secret\ mkdir Qt-Secret\ & if not exist Qt-Secret\ exit 1
	cd Qt-Secret\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\Qt-Secret\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-MyProject-benchmark_ordered: sub-Qt-Secret-benchmark_ordered 
	@if not exist MyProject\ mkdir MyProject\ & if not exist MyProject\ exit 1
	cd MyProject\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\qt_proj\auth\MyProject\MyProject.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-benchmark_ordered: sub-MyProject-benchmark_ordered 
	@if not exist Qt-Secret\src\ mkdir Qt-Secret\src\ & if not exist Qt-Secret\src\ exit 1
	cd Qt-Secret\src\ && ( if not exist Makefile.Qt-Secret $(QMAKE) -o Makefile.Qt-Secret C:\qt_proj\auth\Qt-Secret\src\Qt-Secret.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.Qt-Secret benchmark
benchmark: sub-Qt-Secret-benchmark_ordered sub-MyProject-benchmark_ordered sub-C--qt_proj-auth-Qt-Secret-src-Qt-Secret-pro-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

